### ISSUE TITLE
How do you run this on nullbernetes ?

### ISSUE THREAD

**Issue by sokoow** [kelseyhightower/nocode#2858]
It'd be nice for somebody to write manifests to support nullbernetes and the brand new null kernel namespace.

**Comment by eduardobaitello** [comment]
```
apiVersion: v0
kind: Pod
metadata:
  name: nocode
  namespace: null
spec:
  containers:
  - name: no-code
    image: kelseyhightower/nocode:nullest
    resources:
      limits:
        memory: "0Mi"
        cpu: "0m"
      requests:
        memory: "0Mi"
        cpu: "0m"
    command: ["0"]
    args: [">", "/dev/null"]
```
